

import { Toaster } from "sonner";
import "./styles/scss/base/_fonts.scss";
import "./styles/scss/theme_styles.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>


        {children}
        <Toaster richColors/>
      </body>
    </html>
  );
}
